config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'static_pages/home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'

  resources :microposts
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root 'application#hello'
  root 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def hello
    render html: "¡Hola, mundo!"
  end
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
 # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "No Me Roben Mi Bici"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    @2017 NMRMB inc.
  </small>
  <nav>
    <ul>
      <li><%= link_to "Privacidad", '#' %></li>
      <li><%= link_to "Acerca de nosotros", '#' %></li>
    </ul>
  </nav>
  <nav>
    <ul>
      <li><%= link_to "Reportar un error", '#' %></li>
      <li><%= link_to "Ayuda", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="headerNmrmb navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "NMRMB", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Buscar",   root_path %></li>
        
        <% if user_signed_in? %>
        <li><%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
        <li style="color: #9d9d9d">Bienvenido <strong><%= current_user.name %></strong>.</li>
        
        <% else %>
        <li><%= link_to "Iniciar sesión", new_user_session_path %></li>
        <% end %>
        
        <li><%= link_to "Contáctanos",   contact_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    
    <!-- Inicio bloque devise muestra que el inicio de sesión fue exitoso o no-->
      <% if notice %>
    	  <p class="alert alert-success"><%= notice %></p>
    	<% end %>
    	<% if alert %>
    	  <p class="alert alert-danger"><%= alert %></p>
    	 <% end %>
    <!-- Fin bloque devise -->      
      
      <%= yield %>
      
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
  <div id="formulario">
        <form class="form-inline" role="form" action="php/contacto.php" method="POST" id="contacto" title="Nombre">
        <label for="nombre">Nombre</label>
        <input class="form-control name=" name="nombre" type="text" required="required" id="nombre" placeholder="nombre" tabindex="1" title="Nombre">
        <br>
        <label for="email">Email</label>
        <input class="form-control name=" name="email" type="email" required="required" id="email" placeholder="email" tabindex="2" title="Email">
        <br>
        <label for="Mensaje">Mensaje</label>
        <textarea class="form-control name=" name="mensaje" rows="7" id="mensaje" placeholder="mensaje" tabindex="10"></textarea>
        <br>
        <input class="btn btn-primary" type="submit" name="enviar" tabindex="7" value="Enviar"><input type="reset" tabindex="8" class="btn btn-primary" value="Borrar">
        <input type="hidden" name="estado" value="1">
        
        </form>
    </div>
    
    <iframe width="300" height="300" frameborder="0" style="border:0"
 src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDvxRYnJWAUmAQycjpdVGm_wu6K70z9HEQ &callback=initMap"
 allowfullscreen>
</iframe>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/help">Rails Tutorial help section</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/home.html.erb
  
  <div class="center">      
  <div class="_style_VRmHw" >
    <div class="_style_1fRwDe" >
      <div style="padding-top:44px;padding-bottom:44px;" class="_style_EFOZ6">
        <div>
          <h1 class="nmrmb" >NMRMB</h1>
          <h1 class="txtImpressive" >Viaja en tu bici,</h1>
          <p class="txtNotImpressive" >Sin miedo.</p>
        </div>
      </div>
    </div>
  </div>
  </div>   
  
  
  <div id="headerwrap">
		<div class="container">
			<div class="row">
				<div class="col-lg-6">
					<h1 style="text-align:left">Ahora podrás reportar<br/>
					 tu bici perdida.</h1>
					<form class="form-inline" role="form">
					  <div class="form-group">
					    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Ingresa tu email">
					  </div>
					  <button type="submit" class="btn btn-warning btn-lg">Enviar email!</button>
					</form>					
				</div><!-- /col-lg-6 -->
				
				<div class="col-lg-6">
					<%= image_tag("ipadhand.png") %>
				</div><!-- /col-lg-6 -->
				
			</div><!-- /row -->
		</div><!-- /container -->
	</div><!-- /headerwrap -->
	
	<div class="row mt centered">
			<div class="col-lg-4">
			  <div class="center">
				  <%= image_tag("ser01.png", size: "100") %>
				</div>
				<h4 class="info">Viaja con seguridad</h4>
				<p class="par">
				  Antes de tomar una ruta puedes revisar si pasa por
				  lugares peligrosos. <br>
				  Analiza las estadisticas relacionadas con tu ruta
				  para planear mejor el viaje.
				</p>
			</div><!--/col-lg-4 -->

			<div class="col-lg-4">
			  <div class="center">
					<%= image_tag("ser02.png", size: "100") %>
					</div>
				<h4 class="info">Reporta hurtos o actividad sospechosa</h4>
				<p class="par">
				  Puedes reportar al instante actividad sospechosa. <br>
				  Esta pequeña acción puede alertar a otros biciusuarios.
				</p>

			</div><!--/col-lg-4 -->

			<div class="col-lg-4">
			  	<div class="center">
				    <%= image_tag("ser03.png", size: "100") %>
					</div>
				<h4 class="info">Ayuda a otros a recuperar sus pertenencias</h4>
					<p class="par">
				  Sí tienes información sobre el paradero de un objeto hurtado 
				  puedes informar al biciusuario que realizó el reporte.
				</p>

			</div><!--/col-lg-4 -->
		</div><!-- /row -->
	
  
 <!-- 
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>
      
      
         
            
            -->
            
           
            